CREATE TABLE IF NOT EXISTS parts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  nome_peca VARCHAR(255) NOT NULL,
  preco_custo DECIMAL(10,2) NOT NULL,
  preco_venda DECIMAL(10,2) NOT NULL,
  quantidade_disponivel INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_parts_nome_peca (nome_peca)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
