# This is the Apache configuration file for the Docker container. 
# It sets up a virtual host that listens on port 80 and serves the Laravel application from the 
# /var/www/html/public directory. It also configures the error log and custom log to write to 
# the standard error and standard output, respectively, which is useful for debugging and monitoring 
# the application when running in a Docker container. The Directory directive allows all requests to 
# the public directory and enables .htaccess overrides, which is necessary for Laravel's routing to 
# work properly.

<VirtualHost *:80>
    DocumentRoot /var/www/html/public
    <Directory /var/www/html/public>
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>